### ISSUE TITLE
Is the competition Herbarium 2020  dead ?

### ISSUE THREAD

**Issue by mrT23** [visipedia/herbarium_comp#2]
@kiatchuan 
All the scores in the leaderboard are way too low, ~1e-5, while F1-macro score should be ~1e-1.
there are almost no new daily submissions, and questions in the discussion forum are not answered.

if the competition is dead, please send proper notification. we spent time to download and process this big dataset.

**Comment by kiatchuan** [comment]
Thanks for the feedback! We're currently looking into this issue and will update within the next few days. The competition is still active, thanks for your interest and participation!

**Comment by kiatchuan** [comment]
The new solution mapping file has been uploaded. Submissions have been rescored and the leaderboard updated accordingly. Thanks for raising this issue!
